version: '2.3'
services:

  redis:
    container_name: twig_your_health_redis
    restart: always
    image: redis:latest
    expose:
    - "6379"

#  db:
#    image: postgres:latest
#    container_name: twig_your_health_db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_DB: postgres
#      POSTGRES_HOST_AUTH_METHOD: trust
#    expose:
#    - 5432

  web:
    container_name: twig_your_health_django
    build:
      args:
      - no_static=1
      context: ../
      dockerfile: docker/backend.Dockerfile
    command: bash -c "gunicorn wsgi -b 0.0.0.0:8000 --env DJANGO_SETTINGS_MODULE=base_settings"
    depends_on:
    - redis
    volumes:
    - ../twig_your_health:/srv/TwigYourHealth/twig_your_health
    - ../files:/srv/TwigYourHealth/files
    ports:
    - 8000:8000



