version: '2.3'
services:

  redis:
    container_name: twig_your_health_redis
    restart: always
    image: redis:latest
    expose:
    - "6379"

  db:
    image: postgres:latest
    container_name: twig_your_health_db
    expose:
    - 5432

  web:
    container_name: twig_your_health_django
    build:
      args:
      - no_static=1
      context: ../
      dockerfile: docker/backend.Dockerfile
    command: bash -c "daphne -b 0.0.0.0 -p 8000 development_asgi:application"

    depends_on:
    - db
    - redis
    volumes:
    - ../twig_your_health:/srv/TwigYourHealth/twig_your_health
    - ../files:/srv/TwigYourHealth/files
    ports:
    - 8000:8000



