version: '2.3'
services:

  redis:
    restart: always
    image: redis:latest
    expose:
    - "6379"

  db:
    image: postgres:latest
    container_name: ps01
    expose:
    - 5432

  web:
    build:
      args:
      - no_static=1
      context: ../
      dockerfile: docker/backend.Dockerfile
    command: bash -c "(ls && python manage.py reset_staging --settings=base_settings  && python manage.py runserver 0.0.0.0:8000 --settings=base_settings)"
    depends_on:
    - db
    volumes:
    - ../twig_your_health:/srv/TwigYourHealth/twig_your_health
    - ../files:/srv/TwigYourHealth/files
    ports:
    - 8000:8000



